name: Docker

on:
  workflow_call:

jobs:
  docker:
  runs-on: 'ubuntu-latest'
  steps:
  - uses: actions/checkout@v3
  name: setup docker build
    uses: docker/setup-buildx-action@v2.0.0

  name: Docker Login
    uses: docker/login-action@v3.0.0
    with:
      username: samuellsilva
    # Password or personal access token used to log against the Docker registry
      password: # optional
    # Specifies whether the given registry is ECR (auto, true or false)
              
